# -*- coding: utf-8 -*-
"""P1_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yt9nYIhYdj3hwrVtP0dS1eOxwxs5b1Uo
"""

x1, y1 = input().split()
x2, y2 = input().split()
x = abs(int(x1) - int(x2))
y = abs(int(y1) - int(y2))
if x > 1 or y > 1:
  print('No')
elif x == 0 and y == 0:
  print('No')
elif checkerboard[int(x2)][int(y2)] == 1:
  print('No')
else:
  print('Yes')